# Generated by Django 5.0.1 on 2024-02-04 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('bank_name', models.CharField(max_length=200)),
                ('bank_account', models.CharField(max_length=200)),
                ('whatsapp_number', models.CharField(max_length=200)),
            ],
        ),
    ]
